# Summary of triangular solves and LU factorization in Python for dense and sparse matrices

In [2]:
import numpy
import scipy

## Triangular solves

---
### Dense matrices

In [5]:
A = numpy.array([[3.0, 0.0, 0.0, 0.0], 
                 [2.0, 1.0, 0.0, 0.0], 
                 [1.0, 0.0, 1.0, 0.0], 
                 [1.0, 1.0, 1.0, 1.0]])
b = numpy.array([4.0, 2.0, 4.0, 2.0])

In [6]:
print('A', A)

A [[3. 0. 0. 0.]
 [2. 1. 0. 0.]
 [1. 0. 1. 0.]
 [1. 1. 1. 1.]]


In [7]:
x = scipy.linalg.solve_triangular(A, b, lower=True)

In [8]:
print('x', x)

x [ 1.33333333 -0.66666667  2.66666667 -1.33333333]


---
### Sparse matrices

In [10]:
A = numpy.array([[3.0, 0.0, 0.0, 0.0], 
                 [2.0, 1.0, 0.0, 0.0], 
                 [1.0, 0.0, 1.0, 0.0], 
                 [1.0, 1.0, 1.0, 1.0]])
b = numpy.array([4.0, 2.0, 4.0, 2.0])

In [11]:
# Convert to CSR
As_csr = scipy.sparse.csr_array(A)
print(As_csr)

  (0, 0)	3.0
  (1, 0)	2.0
  (1, 1)	1.0
  (2, 0)	1.0
  (2, 2)	1.0
  (3, 0)	1.0
  (3, 1)	1.0
  (3, 2)	1.0
  (3, 3)	1.0


In [12]:
x = scipy.sparse.linalg.spsolve_triangular(As_csr, b)

In [13]:
print('x', x)

x [ 1.33333333 -0.66666667  2.66666667 -1.33333333]


## LU solve

This function use LU factorization but do not give you direct access to the $\mathbf L$ and $\mathbf U$ factors. These methods are not suited to solve problems involving many right-hand-side vectors in which $\mathbf A$ remains constant.

---
### Dense matrices

In [16]:
A = numpy.array([[ 3.0 ,  2.0 , -1.0 ],
                 [ 2.0 , -2.0 ,  4.0 ],
                 [-1.0 ,  0.5,  -1.0 ]])
b = numpy.array([1.0, -2.0, 0])

In [17]:
x = scipy.linalg.solve(A, b)

In [18]:
print('x', x)

x [ 1. -2. -2.]


---
### Sparse matrices

In [20]:
A = numpy.array([[ 3.0 ,  2.0 , -1.0 ],
                 [ 2.0 , -2.0 ,  4.0 ],
                 [-1.0 ,  0.5,  -1.0 ]])
b = numpy.array([1.0, -2.0, 0])

In [21]:
# Convert to CSR or CSC
As_csr = scipy.sparse.csr_array(A)
print(As_csr)

  (0, 0)	3.0
  (0, 1)	2.0
  (0, 2)	-1.0
  (1, 0)	2.0
  (1, 1)	-2.0
  (1, 2)	4.0
  (2, 0)	-1.0
  (2, 1)	0.5
  (2, 2)	-1.0


In [22]:
x = scipy.sparse.linalg.spsolve(A, b)

/var/folders/8s/2f2dl56n2z5fstgwsqb7yf1m0000gn/T/ipykernel_38415/1921780061.py:1: SparseEfficiencyWarning: spsolve requires A be CSC or CSR matrix format
  x = scipy.sparse.linalg.spsolve(A, b)


In [23]:

print('x', x)

x [ 1. -2. -2.]


## LU factorization + solve

This function use LU factorization. They provide access to the $\mathbf L$ and $\mathbf U$ factors hence they can be used to efficiently solve problems with multiple right-hand-side vectors.

---
### Dense matrices

In [26]:
A = numpy.array([[ 3.0 ,  2.0 , -1.0 ],
                 [ 2.0 , -2.0 ,  4.0 ],
                 [-1.0 ,  0.5,  -1.0 ]])
b = numpy.array([1.0, -2.0, 0])

Perform the LU factorization

In [28]:
lu, piv = scipy.linalg.lu_factor(A)

Apply the action of the inverse of $\mathbf L$ and $\mathbf U$ on $\mathbf b$

In [30]:
x = scipy.linalg.lu_solve((lu, piv), b)

In [31]:
print('x', x)

x [ 1. -2. -2.]


---
### Sparse matrices

In [33]:
Ad = numpy.array([[ 3.0 ,  2.0 , -1.0 ],
                  [ 2.0 , -2.0 ,  4.0 ],
                  [-1.0 ,  0.5,  -1.0 ]])
b = numpy.array([1.0, -2.0, 0])

In [34]:
# Convert Ad to sparse of type CSC or CSR
As_csc = scipy.sparse.csc_array(A)
As_csr = scipy.sparse.csr_array(A)

In [35]:
solve = scipy.sparse.linalg.factorized(As_csc) # Makes LU decomposition for CSC
x = solve(b) # Uses the LU factors.

In [36]:
print('x', x)

x [ 1. -2. -2.]


In [37]:
solve = scipy.sparse.linalg.factorized(As_csr) # Makes LU decomposition for CSR
x = solve(b) # Uses the LU factors.

/opt/anaconda3/lib/python3.12/site-packages/scipy/sparse/linalg/_dsolve/linsolve.py:603: SparseEfficiencyWarning: splu converted its input to CSC format
  return splu(A).solve


In [38]:
print('x', x)

x [ 1. -2. -2.]
