# Python for Numerical Methods - Part 2

## Objectives

In this tutorial you will learn 
* How to write functions in Python
* How to manage multiple variables with Python's collection objects (`list`, `tuple`)
* How to create and manipulate arrays using NumPy

---
## Functions

A **function** (in general) performs a **sequence of operations** on some **inputs** and produces a **result (or results)**. 
This may be written as

$$
    \mathcal F(x_1, x_2, \dots, x_M) = y_1, y_2, \dots, y_N.
$$
In the above the function is $\mathcal F$, the inputs are $x_1, \dots, x_M$ and the results are $y_1, \dots, y_N$.

Let's consider a concrete example which will then implement in Python. Consider implementing 
$$
z = x + y + 1
$$
as a function. The functions inputs are $x, y$, the output is $z$ and the function essentially "adds" the inputs and then adds 1 to that result. Let's call the function `adder`

In Python we put everything together like this:

``` python
def adder(x, y):
    var1 = x + y
    z = var1 + 1
    return z
```


Some comments:
* `def` tells Python we are writing a function.
* Like `if`, `for`, the function definition line ends in a `:`.
* The indendation level matters. Code considered within the function must be indented the same way.
* `return` is the keyword used to send any variables trailing `return` back to the caller code (the code calling the function).

Let's see it in usage

In [6]:
# Define the function
def adder(x, y):
    var1 = x + y
    z = var1 + 1
    return z

In [8]:
# Caller code
a = 1.0
b = 2.0

# Pass inputs `a` and `b` (also called arguments) into `adder`
result = adder(a, b) # Capture the variable returned by `adder` in the variable `result`
print(result)

4.0


Note that the input variable names in the caller code (here `a` and `b`) do not have to match the names of the input variables used to define the function (here `x` and `y`). The same is true for the returned result of the function (`z` was used in the function definition, whilst `result` was used in the caller code)

Functions with multiple variables returned is easy in Python

In [12]:
# Define the function
def add_each(x, y):
    z1 = x + 2
    z2 = y**2 + 2
    return z1, z2

In [14]:
# Caller code
a = 1.0
b = 2.0

# Pass inputs `a` and `b` (also called arguments) into `add_each`
result1, result2 = add_each(a, b) # Capture the variable returned by `adder` in the variable `result`
print(result1, result2)

3.0 6.0


A Python function does not **have** to explicitly call `return`. If you omit returning any variables Python will automatically return a special data type called `None`.

In [17]:
def printer_func(x):
    print('just printing input...', 'x =', x)
    # no return called here

In [19]:
# Caller code
a = 12.0

result = printer_func(a)

just printing input... x = 12.0


In [21]:
print('result =', result)

result = None


### Mismatched numnber of input or output args

If you mess up, don't worry, Python will let you know.

**1.** If you use too many input arguments, this will happen

In [25]:
result = printer_func(1.0, 2.0)

TypeError: printer_func() takes 1 positional argument but 2 were given

Translation, the function expected one arguement ("1 positional argument") however you provided two ("2 were given")

**2.** If you do not have enough input arguments, this will happen

In [28]:
result1, result2 = add_each(1.0)

TypeError: add_each() missing 1 required positional argument: 'y'

**3.** If you have too many output arguments, this will happen

In [31]:
result1, result2 = printer_func(a)

just printing input... x = 12.0


TypeError: cannot unpack non-iterable NoneType object

The messagae is less clear, but failure to "unpack" means Python could not shove the outputs into the variables you had next to the function call.

**4.** If you do not have enough output arguments

In [35]:
result = add_each(1.0, 2.0)

This one is sneaky. The call worked without error, however `result` is possibly not what you expected. Check its type

In [38]:
print(type(result))

<class 'tuple'>


A `tuple` is a type of collection (we will learn more about this in the next section).
Printing `result` we see that in fact the numbers inside the `tuple` are correct, however the expected numbers have been packed inside some data type.

In [41]:
print(result)

(3.0, 6.0)


---
## Collections: `list` and `tuple`

Python natively provides several data structures to support collections of variables.

The first of these we will discuss is called `list`.

### The `list` object

Below is an example code defining a `list` of integers

In [46]:
var_1 = [ 1, 2, 55, -2, 32 ]

Python figures out we want to create a `list` by the **square** parenthesis (`[` and `]`). Within the open and closed square parenthesis we comma separate all the elements we wish to include in our `list`.

Printing `list`s is simple

In [49]:
print(var_1)

[1, 2, 55, -2, 32]


Let's check the data type of `var_1` just to be sure we got what we expected

In [52]:
print('var_1 is a', type(var_1))

var_1 is a <class 'list'>


One thing that is useful about `list`s is that you don't have to know in advance what you will put it them at the time the variable is declared. We can create an empty `list` and then append elements to it. For example

In [55]:
var_2 = list() # This is an empty list
print(var_2) # Check it's empty

[]


In [57]:
var_2.append(1) # Insert the integer 1 into the list

In [59]:
print(var_2)

[1]


In [61]:
var_2.append(2)
var_2.append(55)
var_2.append(-2)
var_2.append(32)
print('var_2 now contains', var_2, 'which should be identical to var_1', var_1)

var_2 now contains [1, 2, 55, -2, 32] which should be identical to var_1 [1, 2, 55, -2, 32]


Note that `list`s can store any kind of data type you like. 

You can access the element of a `list` like this

In [64]:
z = var_1[0] # Access the first element in var_1
print(z)

1


In [66]:
z = var_1[1] # Access the second element in var_1
print(z)

2


Takehome message - Python uses **0-based** indices for collections and everything else.

### The `tuple` object

Below is an example code defining a `tuple` of integers

In [70]:
var_1_t = ( 1, 2, 55, -2, 32 )

Python figures out we want to create a `tuple` by the **round** parenthesis (`(` and `)`). Within the open and closed round parenthesis we comma separate all the elements we wish to include in our `tuple`.

Printing `list`s is simple

In [73]:
print(var_1_t)

(1, 2, 55, -2, 32)


The big difference between the `tuple` and the `list` is that the `tuple` cannot be extended or changed once it is created. You cannot create an empty `tuple` and then `.append()` elements into it.

When you have more than one input arguments to function, internally Python can handle these a tuple.
When a function `return`s more than one variable, these can also be handled via a `tuple`.

Let's summarize:
* If you have a function with more than one argument (say `x`, `y`, `z`) and when calling it you pass in one variable (say `input`), Python will treat `input` as if it were a `tuple` and try to *unpack* it into `x`, `y`, `z`.
* If you have a function returning more than one variable (say `r1`, `r2`, `r3`) and when calling it you capture the output in one variable (say 'result'), Python will *pack* `r1`, `r2`, `r3` into a `tuple`.

---
## Arrays with `numpy`

Arrays are fundemental objects in numnerical methods. Support for arrays is best provided using the Python package NumPy (`numpy`).

Like the `math` and `cmath` packages, we will need to `import numpy` to be able to use its array functionality.

In [80]:
import numpy

To create an array there are several possibilities

1. Create an empty array of length $N$. By default the array will be filled with zeros.
2. Create an array using a `list`.

An example of Option 1 is shown below

In [84]:
N = 4               # Set the length of the array to be 4
x = numpy.zeros(N)  # Create the empty array
print(x)            # Print the array

[0. 0. 0. 0.]


In [86]:
# Check the type
print('type(x)', type(x))

type(x) <class 'numpy.ndarray'>


While `print(x)` displays something to the screen which looks like it might be a `list`, `type(x)` confirms it is not, rather it's data type is `ndarray`.

Here is an example of Option 2.

In [90]:
data = [ 1.1, 2.2, 4.4, 1.0e-3 ] # input data given as a list of real (float) numbers

In [92]:
y = numpy.array( data )

In [94]:
print(y)

[1.1e+00 2.2e+00 4.4e+00 1.0e-03]


In the above code, we give `numpy.array()` our `list` variable (here called `data`) and it takes the contents of the list and inserts them into an `ndarray`.

Now we know how to create 1-D arrays. 2-D arrays (actually $N$-D arraus) can also be created.
To create a 2-D array of dimensions $4 \times 3), e.g. for rows and 3 columns we do this

In [98]:
nrows = 4                          # Number of rows
ncols = 3                          # Number of columns
A = numpy.zeros( [nrows, ncols] )  # Create the empty array, providing the number of rows, columns
print(x)                           # Print the array

[0. 0. 0. 0.]


To access or set $i,j$ entries within `A`, we use `A[i, j]`. For example

In [101]:
A[2, 1] = 4

will set the value in row 3, column 2 to 4.0. Remember Python uses 0-based indices. Check with `print()`

In [104]:
print(A)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 4. 0.]
 [0. 0. 0.]]


Lastly, it is helpful to know how to check the dimension, length of each dimension and data type stored in an `ndarray`.

We know how to check something is an `ndarray`. Let's see it again

In [108]:
if isinstance(A, numpy.ndarray):
    print('A is an ndarray')

A is an ndarray


To check the dimension of an `ndarray`, use `.ndim`.

In [111]:
print(A.ndim) # Check A is a 2-D array

2


To check the length of each dimension, use `.shape`.

In [114]:
print(A.shape) # Chcek A has 4 rows and 3 columns

(4, 3)


To know what the data type is of the elements within an `ndarray`, use `.dtype` (short for data type). For `A` we find

In [117]:
print(A.dtype)

float64


`float64` is a double precision floating point number, something you would use to represent real numbers.

When creating `ndarray`, one can choose the data type. Here is how to create an empty $2 \times 2$ array of integers

In [121]:
Ai = numpy.zeros( [2, 2], dtype=numpy.int32 )

In [123]:
print(Ai)

[[0 0]
 [0 0]]


In [125]:
print(Ai.dtype)

int32


Here we force real numbers be used in a 2-D array

In [128]:
Ar = numpy.zeros( [2, 2], dtype=numpy.float64 )
print(Ar.dtype)

float64


By default `ndarray`s created using `.zeros` will use `float64`.

---
## Operations with `ndarray`s

There is something pretty neat you *can* do with `ndarrays`. 
Suppose I have two vectors
$$
x = (1, 2, 3), \quad y = (4, 5, 6)
$$
and I wanted to compute $z = x + y$. We can do this using loops. 

First I create $x$ and $y$.

In [133]:
x = numpy.array( [1.0, 2.0, 3.0] )
y = numpy.array( [4.0, 5.0, 6.0] )

Then I create an empty array of length 3

In [136]:
z = numpy.zeros(3)

Then I loop though indices $0, 1, 2$ and add each $z_i = x_i + y_i$, which in Python will look like `z[i] = x[i] + y[i]`.

In [139]:
for i in range(0, 3):
    z[i] = x[i] + y[i]

In [141]:
print('z =', z)

z = [5. 7. 9.]


Ok - that is clear. Numpy lets you do all this in one-liner. For example do this

In [143]:
z_all_at_once = x + y

results in 

In [147]:
print('z_all_at_once =', z_all_at_once)

z_all_at_once = [5. 7. 9.]


which is exactly the same as `z`.

When you do `+` between two `ndarray`s of the same length, NumPy will execute the loop for you.

This can be pretty handy, and makes for less code for you to write. 
Of course it can also be quite confusing until you get used to it.

When dealing with a complicated algorithm, I strongly suggest you always write loop-based code first, get the algorithm working, then think about using the nice NumPy trick later.

Here is a situation where the numpy trick is really handy, and simple(ish) to understand.

Suppose I had a collection of angles $\theta = [ 0, 0.1 \pi, 0.4 \pi, 0.5\pi, 1.1 \pi]$ and I wanted to compute `\sin()` on each angle. We can do this in one-line using an `ndarray` storing all the angles, and using **NumPy**'s $\sin()$ function (not this will NOT work if you use math.sin()).

In [153]:
thetas = numpy.array(  [0.0, 0.1*numpy.pi, 0.4*numpy.pi, 0.5*numpy.pi, 1.1*numpy.pi]  )

In [155]:
sin_thetas = numpy.sin( thetas )

In [157]:
print('sins ', sin_thetas)

sins  [ 0.          0.30901699  0.95105652  1.         -0.30901699]


Just to make the point about mixing data structures between Python packages and functions from different packages. Below I `import math` and try and give it our `ndarray` of angles. It doesn't work with the message `only length-1 arrays can be converted to Python scalars`

In [160]:
import math

math.sin(thetas)

TypeError: only length-1 arrays can be converted to Python scalars

---
## Complex numbers and `ndarrays`

Lets first create a `list` of complex numbers.

In [164]:
zs_l = [ 1.1 + 3j, 3.3 + 5j ]

We can create a complex array with NumPy like this

In [167]:
zs = numpy.array(zs_l)

In [169]:
print(zs)

[1.1+3.j 3.3+5.j]


Note that this is identical to how arrays of real numbers were created. The only difference is what was in the input `list` passed to `numpy.array`. Let's check the type of `zs` and the data type used *within* `zs`.

In [172]:
print(type(zs), zs.dtype)

<class 'numpy.ndarray'> complex128


So we can see that the type NumPy uses to represent complex numbers where the real and imaginary parts are themselves real numbers is `complex128`. Hence to create an empty 2-D array of complex numbers with size $4 \times 3$ can do achieved like this

In [175]:
Ac = numpy.zeros( (4,3), dtype=numpy.complex128)

In [177]:
print(Ac)

[[0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]]


If you want to manipulate a single element of `Ac`, you can do so like this

In [180]:
Ac[1,1] = 2j

In [182]:
print(Ac)

[[0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+2.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]]


Or like this

In [185]:
Ac[1,1] = 3.0 + 4.0j

In [187]:
print(Ac)

[[0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 3.+4.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]]


 Access to **all** the real entries can achieved using `Ac.real` (for imaginary use `Ac.imag`).

Hence if you want to zero all imaginary parts, you can do this

In [191]:
Ac.imag = 0
print(Ac)

[[0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 3.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]]


Suppose you had a variable `a` and a variable `b` and you wanted to set `Ac[1,1]` to `a + bj`.
This will not work
```python
Ac[1, 1] = a bj
```
The reason is that Python cannot figure out (safely) how to split the `bj` into a variable `b` and the complex number denoted by `j`.
Try it

In [194]:
a = 2.2
b = 3.3
Ac[1,1] = a + bj

NameError: name 'bj' is not defined

Python can only safely understand the notation `j` notation if a number is placed before the `j`.

To achieve what we want we can do this

In [198]:
Ac.real[1,1] = a
Ac.imag[1,1] = b

In [200]:
print(Ac)

[[0. +0.j  0. +0.j  0. +0.j ]
 [0. +0.j  2.2+3.3j 0. +0.j ]
 [0. +0.j  0. +0.j  0. +0.j ]
 [0. +0.j  0. +0.j  0. +0.j ]]


This essentially says "give me all the real elements" and then set the element at "`[1,1]`" to `a` and
"give me all the imaginary elements" and then set the element at "`[1,1]`" to `b`.

---
## Summary

We going to work a lot with array's in this course. Always represent arrays using NumPy's `ndarray` - never use the `list` object in your numerical methods. The only exception is when you have to use a `list` to get quantities into an `ndarray`.

One might ask why we have use `numpy` to manage arrays in Python. The short answer is Python is very general programming language and can be used for many different types of programming tasks. Python was not designed exclusively for numerical methods! However, there are dedicated Python packages which make numerical methods possible. NumPy is one such package.


---
**Please complete the questions in problem set 2 which can be found in `problem_set_2.pdf`**